# Generated by Django 5.1.2 on 2024-11-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
