# Generated by Django 5.1.2 on 2024-12-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_lessonrequest_delete_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='no_of_weeks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
