# Generated by Django 5.1.2 on 2024-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_lessonrequest_no_of_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
