# Generated by Django 5.1.2 on 2024-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_student_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='expertise',
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.CharField(blank=True, choices=[('math', 'Mathematics'), ('english', 'English'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('ict', 'ICT'), ('business', 'Business Studies'), ('economics', 'Economics')], max_length=50, null=True),
        ),
    ]
