# Generated by Django 5.1.2 on 2024-12-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_alter_lessonrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='no_of_weeks',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='AllocatedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('lesson_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lessons', to='tutorials.lessonrequest')),
            ],
            options={
                'unique_together': {('lesson_request', 'occurrence')},
            },
        ),
    ]
