# Generated by Django 5.1.2 on 2024-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subjects',
            field=models.CharField(blank=True, choices=[('algorithms', 'Algorithms'), ('databases', 'Databases'), ('web', 'Web'), ('networks', 'Networks'), ('security', 'Security'), ('ai', 'AI'), ('logic', 'Logic'), ('python', 'Python'), ('java', 'Java')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
